;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        describe-key
        org-cycle
        org-metaright
        org-self-insert-command
        org-shiftright
        paredit-forward-delete
        smex
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        yaml-electric-dash-and-dot
        ))
