;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-grep-or-swiper
	dabbrev-expand
	describe-key
	indent-rigidly
	indent-rigidly-right
	kill-region
	org-cycle
	org-delete-char
	org-force-self-insert
	org-metaright
	org-self-insert-command
	org-shiftright
	paredit-forward-delete
	paredit-splice-sexp-killing-backward
	smex
	yaml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	indent-new-comment-line
	yaml-electric-dash-and-dot
	))
