#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# TRAY ICON SOFTWARE
#

# Start up instant messaging. I rely on Pidgin starting up in it's
# last configuration to start minimized to the system tray
if [ -z "$(pgrep pidgin)" ] ; then
    pidgin &
fi

# Make sure that Dropbox is started
dropbox start

# On login, we unlock the ssh keychain so we're not prompted for
# passphrases later. We pipe /dev/null to ssh-add to make it realize
# it's not running in a terminal. Otherwise, it won't launch the prompt.
#
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

export SSH_ASKPASS="/usr/bin/ssh-askpass"
cat /dev/null | ssh-add &
